### ISSUE TITLE
chests in dungeons sometimes have no loot at all

### ISSUE THREAD

**Issue by mattrix444** [srwaggon/minecraft-roguelike#15]
hi as per your request here is the zippeed config for my install. as a side note i used to have the old greymerk version installed so this config is from that which i presume your mod just overwrites
[roguelike_dungeons.zip](https://github.com/srwaggon/minecraft-roguelike/files/4521615/roguelike_dungeons.zip)
thanks

**Comment by srwaggon** [comment]
I'm sorry that you've encountered this issue. I'm sure it's frustrating.

You're wonderful. You're my favourite type of issue-reporter. I'll investigate this as soon as I get a chance.

In the meantime, I've created a [FAQ](https://github.com/srwaggon/minecraft-roguelike/wiki/Frequently-Asked-Questions#why-are-my-dungeons-empty). Please let me know if it addresses your issue.

**Comment by srwaggon** [comment]
Hey @mattrix444. This should be resolved with [v2.1.2](https://github.com/srwaggon/minecraft-roguelike/releases/tag/v2.1.2).

Although, any already-generated dungeons will unfortunately not be fixed retroactively.

**Comment by srwaggon** [comment]
Fixed in release [`v2.12.2`](https://github.com/srwaggon/minecraft-roguelike/releases/tag/v2.1.2)
