### ISSUE TITLE
No chests, no enemies

### ISSUE THREAD

**Issue by SandwichHorror** [srwaggon/minecraft-roguelike#16]
Fresh install. Zero config modification. About 75% of rooms were missing spawners and chests.

**Comment by srwaggon** [comment]
Thanks for letting me know. This is a common report and definitely an issue inherited from the original fork.

I've created a wiki page for [FAQ](https://github.com/srwaggon/minecraft-roguelike/wiki/Frequently-Asked-Questions#why-are-my-dungeons-empty). Please let me know if it addresses your issue.

As well, some dungeons use the room type `corner` which specifically is an empty room without a chest nor a spawner. In this case, it sounds like this is not the issue you're experiencing.

**Comment by srwaggon** [comment]
@SandwichHorror This should be resolved with [v2.1.2](https://github.com/srwaggon/minecraft-roguelike/releases/tag/v2.1.2).

Although, any already-generated dungeons will unfortunately not be fixed retroactively.

**Comment by srwaggon** [comment]
Fixed in release [`v2.12.2`](https://github.com/srwaggon/minecraft-roguelike/releases/tag/v2.1.2)
