### ISSUE TITLE
[Suggestion] Add a minimum distance to dungeons and vanilla structures (like villages) so they dont collide like this

### ISSUE THREAD

**Issue by BugmanBugman** [srwaggon/minecraft-roguelike#18]
![2020-06-09_17 58 08](https://user-images.githubusercontent.com/40730042/84209853-cbcb8200-aa7c-11ea-8bb6-7e29d0514960.png)

**Comment by srwaggon** [comment]
@V-Boy That would be dope.

I don't know of a way to detect village spawn chunks.

There's some code in the mod that suggests that this is algorithmically possible, but it clearly doesn't work (your photo is evidence enough).
