### ISSUE TITLE
Loot tables

### ISSUE THREAD

**Issue by Blackcomet** [srwaggon/minecraft-roguelike#20]
I replaced the old RLD with this mod, but neither one has anything on the settings folder where the loot tables should be. And Mega Loot items aren't loading into the RLD's. The author for Mega Loot isn't getting back to me if there is a problem with Mega Loot loot tables.

**Comment by Blackcomet** [comment]
Also I want to add other items to RLD specific loot tables but I don't know where to start. I don't want to override vanilla tables completely.

**Comment by srwaggon** [comment]
@Blackcomet
Hmm... If I had to give advice, I'd say to tinker with an established modpack that has examples. Maybe try out the Modpack Roguelike Dungeons & Adventures?

That's the modpack that made me decide to fork this mod.

Try jumping into the discord for more support.

**Comment by srwaggon** [comment]
Closing this issue because it isn't an issue with the mod -- it's a support request.

The discord is a great resource for this type of help!
https://discord.gg/AZYgST2
