### ISSUE TITLE
[Suggestion] Add setting to use own loot tables

### ISSUE THREAD

**Issue by democat3457** [srwaggon/minecraft-roguelike#21]
I know that the mod uses vanilla loot tables to make it easier on modded environments to alter the loot, but if the said modded environment wants *end-specific* loot in end city loot, then the dungeons become an increasingly large progression skip, which is why there should be a setting to, instead of using vanilla loot tables by default, use loot tables separate from vanilla.

**Comment by srwaggon** [comment]
@democat3457 The loot can be entirely customised using settings. :D
