### ISSUE TITLE
Crash?

### ISSUE THREAD

**Issue by NightScale5755** [srwaggon/minecraft-roguelike#22]
Hello. I'm a moderator in a WIP Mohist server. Mohist is a spigot/bukkit bridge.
We're encountering a crash on server start.
https://pastebin.com/Rj2ahsU7

**Comment by Mgazul** [comment]
The latest Mohist build has fixed this problem

**Comment by srwaggon** [comment]
> The latest Mohist build has fixed this problem

closing.
