### ISSUE TITLE
.Json's not parsing

### ISSUE THREAD

**Issue by Drakkenlord534** [srwaggon/minecraft-roguelike#23]
You're mod is being used in the Minecraft Eternal modpack, but isn't loading any of the dungeons. i investigated a bit by running the <Roguelike Dungeon Here Tower> command and it didn't work because the Loot2.Json wasn't parsing due to an unknown error. I tried pulling a .Json from another modpack to replace it and the error still persisted. I then attempted to remove all the loot tables and see if i could get just the dungeon to spawn but it just kept spitting out the same error. despite this however the citadel command still works.
As the maintainer of the mod i figured you might have an idea on what was happening.

**Comment by srwaggon** [comment]
@Drakkenlord534 I've pushed an update which might address this. If you are willing, please check it for me and let me know if it fixes any issues.

**Comment by srwaggon** [comment]
@Drakkenlord534 Thank you for bringing this to my attention. I've reached out to the modpack maintainer and I have advice for them to move forward with this.
