### ISSUE TITLE
Dungeon spawns seem to be absurdly low, if not non-existent

### ISSUE THREAD

**Issue by Sunconure11** [srwaggon/minecraft-roguelike#26]
Unless I spawn one in, I have yet to see a dungeon spawn from this mod, after installing this fork. I am looking all over a Climatic Biomes map, and I have yet to find out.

**Comment by NightSparrow** [comment]
I can confirm dungeons do not spawn. Setting spawn freq to 1 yields nothing. Also trying to spawn own dungeon with command returns Failure: Null. Trying to reload settings also returns an error linked to rooms.class. Both latest version and previous have the same issue

**Comment by srwaggon** [comment]
@NightSparrow It sounds like you have an issue with your configuration. That is not a problem with the mod. Please check the discord server for support. The Discord server can be found here: https://discord.gg/AZYgST2.

**Comment by srwaggon** [comment]
@Sunconure11 There does not sound to be sufficient evidence yet for this to be an issue with the mod. This sounds like a problem on your end, possibly due to another mod. Since you're already speaking with me in discord, I'll close this issue for now as we debug the problem.
